/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <rcon_packet>

#define PLUGIN "New Plug-In"
#define VERSION "1.0.0"
#define AUTHOR "r0ma'"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR);
}

public rcon_packet(const ip[]) {
	// rcon challenge_number password args...
	new argv1[33];
	new argv2[33];
	
	read_argv(3, argv1, 32);
	read_argv(4, argv2, 32);
	server_print("rcon ip %s argv1: %s argv2: %s", ip, argv1, argv2);
	
	// Block sv_restart from rcon
	if(equal(argv1, "sv_restart"))
		return PLUGIN_HANDLED;
	
	return PLUGIN_CONTINUE;
}

public rcon_challenge_packet(const ip[]) {
	// challenge rcon
	new challenge[32], rcon[33];
	
	read_argv(0, challenge, 32);
	read_argv(1, rcon, 32);
	
	server_print("rcon challenge ip %s buffer: %s %s", ip, challenge, rcon);
	
	return PLUGIN_CONTINUE;
}